-- Ensure UUID extension is available
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-------------------------------------------------------------------------------
-- 1. PROFILES TABLE
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  phone_number TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile" 
  ON public.profiles FOR SELECT 
  USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" 
  ON public.profiles FOR INSERT 
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id);

-------------------------------------------------------------------------------
-- 2. SOWS TABLE
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  sow_id TEXT NOT NULL,
  name TEXT NOT NULL,
  tag_number TEXT NOT NULL,
  status TEXT CHECK (status IN ('Healthy', 'Breeding', 'Gestating', 'Isolated')) DEFAULT 'Healthy',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.sows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own sows" ON public.sows FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own sows" ON public.sows FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own sows" ON public.sows FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own sows" ON public.sows FOR DELETE USING (auth.uid() = user_id);

-------------------------------------------------------------------------------
-- 3. GESTATION TASKS TABLE
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.gestation_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  title TEXT NOT NULL,
  description TEXT,
  task_type TEXT DEFAULT 'General',
  task_date DATE NOT NULL,
  task_time TEXT DEFAULT '08:00 AM',
  sow_id TEXT,
  sow_tag_id TEXT,
  priority TEXT CHECK (priority IN ('Low', 'Medium', 'High')) DEFAULT 'Medium',
  status TEXT CHECK (status IN ('Pending', 'Completed', 'Cancelled')) DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.gestation_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own tasks" ON public.gestation_tasks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own tasks" ON public.gestation_tasks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tasks" ON public.gestation_tasks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own tasks" ON public.gestation_tasks FOR DELETE USING (auth.uid() = user_id);

-------------------------------------------------------------------------------
-- 4. APP NOTIFICATIONS TABLE
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

-------------------------------------------------------------------------------
-- 5. REALTIME SUBSCRIPTION ENABLING
-------------------------------------------------------------------------------
ALTER PUBLICATION supabase_realtime ADD TABLE public.sows;
ALTER PUBLICATION supabase_realtime ADD TABLE public.gestation_tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;